language: objective-c
osx_image: xcode8.2
sudo: false

before_install:
  - gem install fastlane

before_script:
  - fastlane snapshot reset_simulators --force

script:
  - xcodebuild clean build test -project FastPod39.xcodeproj -scheme FastPod39 -destination "platform=iOS Simulator,name=iPhone 7,OS=10.2" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

